### ISSUE TITLE
github.com/maseology/mmio IS missing……！

### ISSUE THREAD

**Issue by cyooleoo** [maseology/glbopt#1]
RT

**Comment by maseology** [comment]
dependencies to mmio have been removed

**Comment by cyooleoo** [comment]
1、The &nbsp;other module like rainrun,goHydro,ptrack also&nbsp;dependent on ‘mmio’ !
2、Please give some&nbsp;Example and data, in order to&nbsp;complie and test the&nbsp;modules.


&nbsp; &nbsp; Thanks……！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Mason Marchildon"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月6日(星期一) 晚上10:38
收件人:&nbsp;"maseology/glbopt"<glbopt@noreply.github.com&gt;;
抄送:&nbsp;"卜戈"<14287501@QQ.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [maseology/glbopt] github.com/maseology/mmio IS missing……！ (#1)




dependencies to mmio have been removed
